# Generated by Django 5.2.16 on 2026-10-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriculturalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agricultural Category',
                'verbose_name_plural': 'Agricultural Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='farmerprofile',
            options={'verbose_name': 'Agricultural Business Profile', 'verbose_name_plural': 'Agricultural Business Profiles'},
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='farm_description',
            field=models.TextField(blank=True, help_text='Description of the agricultural business or professional activity.'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='farm_location',
            field=models.CharField(help_text='Primary business or operating location.', max_length=255),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='farm_name',
            field=models.CharField(help_text='Business, farm, organization or professional name.', max_length=255),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='business_categories',
            field=models.ManyToManyField(blank=True, related_name='business_profiles', to='farmers.agriculturalcategory'),
        ),
    ]
