# Generated by Django 5.2.16 on 2026-10-02 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_agriculturalcategory_alter_farmerprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriculturalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, help_text='Service location. Leave blank if the service is available remotely or nationwide.', max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional starting or advertised price.', max_digits=12, null=True)),
                ('price_unit', models.CharField(blank=True, help_text='Examples: per acre, per visit, per hour, per project, per day.', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='farmers.farmerprofile')),
            ],
            options={
                'verbose_name': 'Agricultural Service',
                'verbose_name_plural': 'Agricultural Services',
                'ordering': ['-created_at'],
            },
        ),
    ]
