# Generated by Django 5.2.16 on 2026-10-06 23:16

from django.db import migrations, models
from django.utils.text import slugify


def populate_farmer_profile_slugs(apps, schema_editor):
    FarmerProfile = apps.get_model(
        "farmers",
        "FarmerProfile",
    )

    used_slugs = set()

    profiles = (
        FarmerProfile.objects
        .all()
        .order_by("id")
    )

    for profile in profiles:
        base_slug = (
            slugify(profile.farm_name)
            or "agricultural-business"
        )

        candidate = base_slug
        counter = 2

        while candidate in used_slugs:
            candidate = f"{base_slug}-{counter}"
            counter += 1

        profile.slug = candidate

        profile.save(
            update_fields=["slug"]
        )

        used_slugs.add(candidate)


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        (
            "farmers",
            "0004_seed_agricultural_categories",
        ),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                'DROP INDEX IF EXISTS '
                '"farmers_farmerprofile_slug_3e506825_like";'
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AddField(
            model_name="farmerprofile",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text=(
                    "Stable public URL identity for the "
                    "AgricWise business presence."
                ),
                max_length=280,
            ),
        ),

        migrations.RunPython(
            populate_farmer_profile_slugs,
            migrations.RunPython.noop,
        ),

        migrations.AlterField(
            model_name="farmerprofile",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text=(
                    "Stable public URL identity for the "
                    "AgricWise business presence."
                ),
                max_length=280,
                unique=True,
            ),
        ),
    ]