# Generated by Django 5.2.16 on 2026-10-06 23:16

from django.db import migrations, models
from django.utils.text import slugify


def remove_stale_slug_relation(apps, schema_editor):
    """
    Remove any stale PostgreSQL relation left behind by a previous
    failed attempt to create FarmerProfile.slug.

    PostgreSQL reports indexes, tables, sequences, etc. as relations.
    We therefore inspect the catalog instead of assuming the object
    is specifically an index.
    """

    if schema_editor.connection.vendor != "postgresql":
        return

    relation_name = "farmers_farmerprofile_slug_3e506825_like"

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT c.relkind
            FROM pg_class AS c
            INNER JOIN pg_namespace AS n
                ON n.oid = c.relnamespace
            WHERE n.nspname = 'public'
              AND c.relname = %s
            """,
            [relation_name],
        )

        row = cursor.fetchone()

        if not row:
            return

        relkind = row[0]

        if relkind in ("i", "I"):
            cursor.execute(
                'DROP INDEX IF EXISTS "{}"'.format(
                    relation_name
                )
            )
        elif relkind in ("r", "p", "m", "S"):
            cursor.execute(
                'DROP TABLE IF EXISTS "{}" CASCADE'.format(
                    relation_name
                )
            )


def populate_farmer_profile_slugs(apps, schema_editor):
    FarmerProfile = apps.get_model(
        "farmers",
        "FarmerProfile",
    )

    used_slugs = set()

    profiles = (
        FarmerProfile.objects
        .all()
        .order_by("id")
    )

    for profile in profiles:
        base_slug = (
            slugify(profile.farm_name)
            or "agricultural-business"
        )

        candidate = base_slug
        counter = 2

        while candidate in used_slugs:
            candidate = f"{base_slug}-{counter}"
            counter += 1

        profile.slug = candidate

        profile.save(
            update_fields=["slug"]
        )

        used_slugs.add(candidate)


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        (
            "farmers",
            "0004_seed_agricultural_categories",
        ),
    ]

    operations = [
        migrations.RunPython(
            remove_stale_slug_relation,
            migrations.RunPython.noop,
        ),

        migrations.AddField(
            model_name="farmerprofile",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text=(
                    "Stable public URL identity for the "
                    "AgricWise business presence."
                ),
                max_length=280,
            ),
        ),

        migrations.RunPython(
            populate_farmer_profile_slugs,
            migrations.RunPython.noop,
        ),

        migrations.AlterField(
            model_name="farmerprofile",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text=(
                    "Stable public URL identity for the "
                    "AgricWise business presence."
                ),
                max_length=280,
                unique=True,
            ),
        ),
    ]
