
# Generated by Django 5.2.16 on 2026-10-06 23:16

from django.db import migrations, models
from django.utils.text import slugify


SLUG_COLUMN = "slug"
SLUG_INDEX = "farmers_farmerprofile_slug_3e506825_like"
SLUG_UNIQUE_CONSTRAINT = "farmers_farmerprofile_slug_unique"


def ensure_slug_column(apps, schema_editor):
    """
    Ensure the production database has the slug column.

    The production database may already contain the column because an
    earlier partially-applied version of this migration created it
    before failing later in the migration.
    """

    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = 'farmers_farmerprofile'
              AND column_name = %s
            """,
            [SLUG_COLUMN],
        )

        exists = cursor.fetchone()

        if not exists:
            cursor.execute(
                """
                ALTER TABLE "farmers_farmerprofile"
                ADD COLUMN "slug" varchar(280)
                """
            )


def populate_farmer_profile_slugs(apps, schema_editor):
    FarmerProfile = apps.get_model(
        "farmers",
        "FarmerProfile",
    )

    used_slugs = set()

    profiles = (
        FarmerProfile.objects
        .all()
        .order_by("id")
    )

    for profile in profiles:
        base_slug = (
            slugify(profile.farm_name)
            or "agricultural-business"
        )

        candidate = base_slug
        counter = 2

        while candidate in used_slugs:
            candidate = f"{base_slug}-{counter}"
            counter += 1

        profile.slug = candidate

        profile.save(
            update_fields=["slug"]
        )

        used_slugs.add(candidate)


def ensure_slug_unique(apps, schema_editor):
    """
    Ensure slug is unique in PostgreSQL without assuming that the
    database is completely clean.

    The migration may be recovering from a partially-applied attempt,
    so we first remove known stale objects and then create the unique
    constraint only when it does not already exist.
    """

    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:

        # Remove the stale relation produced by an earlier failed
        # attempt to create the slug field.
        cursor.execute(
            """
            DROP INDEX IF EXISTS
            "farmers_farmerprofile_slug_3e506825_like"
            """
        )

        # Check whether the intended unique constraint already exists.
        cursor.execute(
            """
            SELECT 1
            FROM pg_constraint
            WHERE conname = %s
            """,
            [SLUG_UNIQUE_CONSTRAINT],
        )

        constraint_exists = cursor.fetchone()

        if not constraint_exists:
            cursor.execute(
                """
                ALTER TABLE "farmers_farmerprofile"
                ADD CONSTRAINT "farmers_farmerprofile_slug_unique"
                UNIQUE ("slug")
                """
            )


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        (
            "farmers",
            "0004_seed_agricultural_categories",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    ensure_slug_column,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="farmerprofile",
                    name="slug",
                    field=models.SlugField(
                        blank=True,
                        help_text=(
                            "Stable public URL identity for the "
                            "AgricWise business presence."
                        ),
                        max_length=280,
                    ),
                ),
            ],
        ),

        migrations.RunPython(
            populate_farmer_profile_slugs,
            migrations.RunPython.noop,
        ),

        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    ensure_slug_unique,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="farmerprofile",
                    name="slug",
                    field=models.SlugField(
                        blank=True,
                        help_text=(
                            "Stable public URL identity for the "
                            "AgricWise business presence."
                        ),
                        max_length=280,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
