# Generated by Django 5.2.16 on 2026-10-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0005_farmerprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Whether the business has completed its core setup and intentionally published its AgricWise presence.'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether AgricWise has independently verified this agricultural business.'),
        ),
    ]
