# Generated by Django 5.2.16 on 2026-09-24 12:13

from django.conf import settings
from django.db import migrations, models


def mark_existing_connections_accepted(apps, schema_editor):
    Connection = apps.get_model("community", "Connection")

    Connection.objects.all().update(
        status="accepted"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True
            ),
        ),
        migrations.RunPython(
            mark_existing_connections_accepted,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="connection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("follower", models.F("following")),
                    _negated=True,
                ),
                name="prevent_self_connection",
            ),
        ),
    ]