# Generated by Django 5.2.16 on 2026-09-27 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_connection_status_connection_updated_at_and_more'),
        ('products', '0003_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_post', to='products.product'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('discussion', 'Discussion'), ('knowledge', 'Knowledge'), ('announcement', 'Announcement'), ('question', 'Question'), ('for_sale', 'For Sale'), ('service', 'Service')], default='discussion', max_length=20),
        ),
    ]
