# Generated by Django 5.2.16 on 2026-09-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_post_product_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('discussion', 'Discussion'), ('for_sale', 'For Sale'), ('service', 'Service')], default='discussion', max_length=20),
        ),
    ]
