# Generated by Django 5.2.16 on 2026-09-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='community/posts/videos/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('discussion', 'Discussion'), ('marketplace', 'Marketplace')], default='discussion', max_length=20),
        ),
    ]
