# Generated by Django 5.2.16 on 2026-09-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('registration', 'Registration'), ('product_approval', 'Product Approval'), ('new_order', 'New Order'), ('payment_update', 'Payment Update'), ('delivery_update', 'Delivery Update'), ('connection', 'Connection')], max_length=50),
        ),
    ]
